#!/bin/bash
source $PANEL_CONFIG
while true; do
    now="$(date +"$clock_fmt")"
    if [[ "$now" != "$before" ]]; then
        echo "clock$cmd_ifs $now "
        before="$now"
    fi
    sleep 1
done
