#!/bin/bash
source $HOME/.config/panel/config
[ ! -e /sys/class/net/$netw_iface ] && exit 1

oldsig=""
while true; do
    buf="netw$cmd_ifs"
    sig="$(awk "/$netw_iface:/ { print \$4 }" </proc/net/wireless)"
    if [[ "$sig" != "$oldsig" ]]; then
        if [[ -z "$sig" ]]; then
            echo "$buf$fmt_wifi_off $ico_wifi_off"
        else
            echo "$buf$fmt_wifi $ico_wifi ${sig%.} dBm"
        fi
        oldsig="$sig"
    fi
    sleep 1
done
