#!/bin/bash
source $HOME/.config/panel/config

pull() {
    buf="song$cmd_ifs"
    info="$(mpc current)"
    case `mpc | awk 'NR==2 { print $1 }' | tr -d '[]'` in
        playing)
            buf="$buf$fmt_song_playing"
            ico="$ico_song_playing"
            txt="$info"
            ;;
        paused)
            buf="$buf$fmt_song_paused"
            ico="$ico_song_paused"
            txt="$info"
            ;;
        *)
            buf="$buf$fmt_song_stopped"
            ico="$ico_song_stopped"
            txt=""
            ;;
    esac
    echo "$buf $ico $txt"
}

pull
mpc idleloop | while read; do
    pull
done
