#!/bin/bash
source $PANEL_CONFIG

pull() {
    buf="song$cmd_ifs"
    song=`mpc | awk -F ' - ' 'NR==1 { print $2 }'`
    case `mpc | awk 'NR==2 { print $1 }' | tr -d '[]'` in
        playing)
            buf="$buf$fmt_song_playing"
            ico="$ico_song_playing"
            txt="$song"
            ;;
        paused)
            buf="$buf$fmt_song_paused"
            ico="$ico_song_paused"
            txt="$song"
            ;;
        *)
            buf="$buf$fmt_song_stopped"
            ico="$ico_song_stopped"
            txt=""
            ;;
    esac
    echo "$buf $ico $txt"
}

pull
mpc idleloop | while read; do
    pull
done
