#!/bin/bash
# vim:set syntax=sh:
source $HOME/.config/panel/config
bspc control --subscribe | while read status; do
    echo "$status" | sed -r \
        -e "s/:[^OoFfUu]+$/: /" \
        -e "s/f([^:#\-]+):/%{A:$tag_switch_cmd \1:}$tag_empty%{A} /g" \
        -e "s/[OFU][^:#\-]+:/$tag_current /g" \
        -e "s/o([^:#\-]+):/%{A:$tag_switch_cmd \1:}$tag_occupied%{A} /g" \
        -e "s/u([^:#\-]+):/%{A:$tag_switch_cmd \1:}$tag_urgent%{A} /g" \
        -e "s/^[^:]+:/tags$cmd_ifs /"
done
