#!/bin/bash
source $HOME/.local/panel/config
while true; do
    summary=`timew`
    if [ $? -ne 1 ]; then
        tag="$(echo "$summary" | head -n1 | cut -d' ' -f2-)"
        echo "timew$cmd_ifs$fmt_task$ico_task $tag"
    else
        echo "timew$cmd_ifs"
    fi
    sleep 30
done
