#!/bin/bash
source $HOME/.config/panel/config
if which amixer ; then
    while true ; do
        volinfo=$(amixer get Master | tail -1)
        if [[ "$volinfo" != "$before" ]]; then
            buf="vol$cmd_ifs"
            if grep -wq on <<< "$volinfo" ; then
                buf="$buf$fmt_vol $ico_vol "
                echo "$buf$(awk '{ print $4 }' <<< "$volinfo" | tr -d '[]')"
            else
                echo "$buf$fmt_vol_muted $ico_vol_muted"
            fi
            before="$volinfo"
        fi
        sleep 1
    done
else
    exit 1
fi
