#!/usr/bin/bash
ROOT="$HOME/.local/panel"
source $ROOT/config
source $HOME/.config/colors/colors.sh

# create the socket (and remove if necessary)
[ -e "$fifo" ] && rm "$fifo"
mkfifo "$fifo"

# create the pid file (and kill existing panels if necessary)
[ -e "$pidfile" ] && pkill -P $(cat "$pidfile")
echo $$ >"$pidfile"

# initiate modules
declare -A modules
for module in $ROOT/modules/* ; do
    $module "$@" >"$fifo" &
done

# main loop
while IFS='' read -r cmd; do
    IFS="$cmd_ifs" read -ra infos <<< "$cmd"
    modules[${infos[0]}]="${infos[1]}"

    if [ -z "${modules[msg]}" ]; then
        left="${modules[tags]}"
    else
        left="${modules[msg]}"
    fi
    center="${modules[clock]}"
    right="${modules[timew]}" #"  ${modules[song]}"

    echo "%{l}   $left%{c}$center%{r}$right%{F-}%{F-}%{B-}  "

done <"$fifo" | /usr/bin/lemonbar -n panel -pdg ${width}x${height}+${x}+${y} \
    -o $offset -f "$font_1" -f "$font_2" -f "$font_3" -B $back_color \
    -F $fore_color | $sh &

wid=$(xdo id -a panel)
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ]; do
    sleep 0.05
    wid=$(xdo id -a panel)
    tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
