#!/usr/bin/bash
echo "panel called with ($@) at $(date)" >> "$HOME/foo"

# configuration
source $PANEL_CONFIG
[ -e $PANEL_HOME/prepare ] && source $PANEL_HOME/prepare "$@"

# create the socket
[ -e "$fifo" ] && rm "$fifo"
mkfifo "$fifo"

# kill any existing panels
$PANEL_HOME/kill

# initiate modules
declare -A modules
for module in $PANEL_HOME/modules/* ; do
    $module "$@" >"$fifo" &
done

fmt_parsed="$(echo "$panel_fmt" | sed -r 's/\$([A-Za-z][0-9_A-Za-z]*)\$/\${modules\[\1\]}/g')"
while IFS='' read -r cmd; do
    IFS="$cmd_ifs" read -ra infos <<< "$cmd"
    modules[${infos[0]}]="${infos[1]}"

    eval echo "$fmt_parsed"
done <"$fifo" | $panel | $sh

wait
unset PANEL_HOME
